magicsorter/magicsorter/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^ms/', include('ms.urls', namespace='ms')),
]

magicsorter/ms/urls.py
from django.conf.urls import url, include

from .views import CardDelete

from . import views

#from .models import InstrumentList
#from .views import InstrumentCreate, InstrumentUpdate, 
#from .views import InstrumentDelete, RuleDelete, PeriodDelete

urlpatterns = [
    url(r'^$', views.cards, name='cards'),
    url(r'^(?P<sort>-*[a-z]+)/$', views.cards, name='cards'),
    url(r'^card/(?P<pk>[0-9]+)/$', views.card, name='card'),
    url(r'^card_delete/(?P<pk>[0-9]+)/$', CardDelete.as_view(), name='card_delete'),
    
    url(r'^scans/(?P<filter>-*[a-z]+)/$', views.scans, name='scans'),
    url(r'^scan_delete/(?P<pk>[0-9]+)/$', views.scan_delete, name='scan_delete'),
    url(r'^scan_mismatch/(?P<pk>[0-9]+)/$', views.scan_mismatch, name='scan_mismatch'),
]

magicsorter/ms/models.py
from django.db import models

from django.forms import ModelForm
from django.views.generic import ListView
from django.views.generic import DetailView

# Create your models here.
class Card(models.Model):
    image = models.ImageField(upload_to='cards')
    thumb = models.ImageField(upload_to='thumbs')
    hist = models.TextField(blank=True)
    #hist = cv2.calcHist([img],[0],None,[256],[0,256])
     
    name = models.CharField(max_length=255, blank=True)
    price = models.FloatField(blank=True, default=0)
    
    count = models.IntegerField(blank=True, default=0)
    outbox = models.IntegerField(blank=True, default=0)
    
    mtgcode =  models.IntegerField(null=True)
    rarity = models.CharField(max_length=255)
    

    
class CardForm(ModelForm):
    class Meta:
        model = Card
        fields = ['image', 'thumb', 'name', 'price', 'count', 'outbox', 'mtgcode', 'rarity']

    
class Scan(models.Model):
    position = models.IntegerField(blank=True, default=0)
    fk_card = models.ForeignKey(Card)
    outbox = models.IntegerField(blank=True, default=0)
    mismatch = models.BooleanField(blank=True, default=False)
    #result0 = models.FloatField(blank=True, default=0)
    #result1 = models.FloatField(blank=True, default=0)
    
    image = models.ImageField(upload_to='scans', blank=True)
    
# Receive the pre_delete signal and delete the file associated with the model instance.
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver

@receiver(pre_delete, sender=Card)
def card_delete(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    instance.image.delete(False)
    instance.thumb.delete(False)

@receiver(pre_delete, sender=Scan)
def scan_delete(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    instance.image.delete(False)

magicsorter/ms/views.py
from django.shortcuts import render

from .models import Card, Scan
from .models import CardForm

from django.template import RequestContext, loader

from django.db import connection, transaction

from django.http import HttpResponse
from django.http import HttpResponseRedirect

from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView

# Create your views here.

class CardDelete(DeleteView):
    model = Card
    success_url = reverse_lazy('ms:cards')
    
    #def deleteq(self, request, *args, **kwargs):
    #    response = super(CardDelete, self).delete(request, *args, **kwargs)
    #    card = self.get_object()
     #   print card.id
    #    Scan.objects.filter(fk_card_id=card.id).update(fk_card_id=0)
     #   card.delete()
    #    return response
    
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        Scan.objects.filter(fk_card_id=self.object.id).update(fk_card_id=0)
        self.object.delete()
        return HttpResponseRedirect(self.get_success_url())
    #card = DeleteView.get_object(self)
    #print card.id
    #Scan.objects.filter(fk_card_id=card.id).update(fk_card_id=0)
    
  
def scans(request, filter='all'):
    if filter == 'mismatch':
        scans = Scan.objects.filter(mismatch=True) #.order_by(sort)
    else:
        scans = Scan.objects.all()
        
    context = RequestContext(request, {
            'scans': scans })
    return render(request, 'ms/scans.html', context)

 

def cards(request, sort='-count'):
    # Data retrieval operation - no commit required
           
    #cursor = connection.cursor()
    #cursor.execute('SELECT * FROM ms_card WHERE 1')# [self.baz])
    #row = cursor.fetchone()
    #print row
    #cards = cursor.fetchall()
    #print cards
    
    
    #for field in Card._meta.fields:
    #    print field.get_attname_column()
    
    if sort=='all':
        cards = Card.objects.order_by('pk')  
    else:
        cards = Card.objects.filter(count__gt=0).order_by(sort)
    #cards = Card.objects.order_by('-count')
    
    
    
    #for card in cards:
    #    card.count = Scan.objects.filter(fk_card=card).count()



    
    
    context = RequestContext(request, {
            'cards': cards })
    return render(request, 'ms/cards.html', context)

def scan_delete(request, pk):
    scan = Scan.objects.get(pk=pk)
    
    c = Card.objects.get(pk=scan.fk_card_id)
    c.count = c.count - 1 
    c.save()
    
    scan.fk_card_id = 0
    scan.save()
    
    return card(request, c.pk)

def scan_mismatch(request, pk):
    scan = Scan.objects.get(pk=pk)
    scan.mismatch = True
    scan.save()
    c = Card.objects.get(pk=scan.fk_card_id)
    return card(request, c.pk)
 
    
def card(request, pk):
    if pk=='0':
        scans = Scan.objects.filter(fk_card_id=0).order_by('position')
        #scans = Scan.objects.order_by('order')
        context = RequestContext(request, {
            'scans': scans })
        return render(request, 'ms/card.html', context) 
    
    card = Card.objects.get(pk=pk)
    form = CardForm(instance = card)
    
    if request.method == 'POST':
        print request.POST
        if 'save' in request.POST:
            form = CardForm(request.POST, instance=card)
            card.name = form.data['name']
            card.price = form.data['price']
            card.save()
            return HttpResponseRedirect('/ms/card/'+str(pk))
            #if form.is_valid():
            #    form.save() 
            #    return HttpResponseRedirect('/ms/card/'+str(pk))
              
    
    scans = Scan.objects.filter(fk_card=card).order_by('position')
   
    print "Mismatch / Total: " + str(Scan.objects.filter(mismatch=True).count()) + ' / ' + str(Scan.objects.count())
     
    
    context = RequestContext(request, {
            'form': form,
            'card': card,
            'scans': scans })
    return render(request, 'ms/card.html', context)  

magicsorter/ms/templates/ms/base.html
<html>
	<head>
		<title>Magic Sorter</title>
		
    </head>

	<body>
   		<h3>
			Cards sort by 	
            <a href="{% url 'ms:cards' 'rarity' %}">Rarity</a>
			
   			<a href="{% url 'ms:cards' %}">Count</a>
			<a href="{% url 'ms:cards' 'pk'  %}">Id</a>
			<a href="{% url 'ms:cards' 'name'  %}">Name</a>
			<a href="{% url 'ms:cards' '-price'  %}">Price</a>
			
 			<a href="{% url 'ms:card' 0 %}">Removed</a>
 			
 			<a href="{% url 'ms:cards' 'all' %}">All</a>
            
    
 			
 		</h3>
        <h3>
            Scans filter 
            <a href="{% url 'ms:scans' 'mismatch' %}">Mismatch</a>
            <a href="{% url 'ms:scans' 'all' %}">All</a>
        </h3>
        
	{% if form %}
		{% if form.errors %}<p><strong>{{ form.errors }}</strong></p>{% endif %}
	{% endif %}
	
       {% block content %}

       {% endblock %} 
    </body>
</html>

magicsorter/ms/templates/ms/card.html
{% extends 'ms/base.html' %}

{% block content %}

{% load staticfiles %}

{% if card %}
<table>
<tr><td>
    
<table border="1">

		<form action="" method="post">{% csrf_token %}
					<tr>
						<td colspan="2">
							<a href="{% static card.image.name %}"><img src="{% static card.thumb.name %}" /></a>
						</td>
					</tr>
					<tr>
						<td>
							Id
						</td>
						<td>
							{{card.id}}
						</td>
					</tr>
					<tr>
						<td>
							Count
						</td>
						<td>
							{{card.count}}
						</td>
					</tr>
					<tr><td>Outbox</td><td>{{card.outbox}}</td></tr>
					<tr>
						<td>
							Name
						</td>
						<td>
							{{form.name}}
						</td>
					</tr>
					<tr>
						<td>
							Price
						</td>
						<td>
							{{form.price}}
						</td>
					</tr>
                    <tr>
						<td>
							MTG code
						</td>
						<td>
							{{card.mtgcode}}
						</td>
					</tr>
                    <tr>
						<td>
							Rarity
						</td>
						<td>
							<b>{{card.rarity}}</b>
						</td>
					</tr>
					<tr><td></td><td><input type="submit" name="save" value="Save!" /></td></tr>
					<tr><td></td><td><a href="{% url 'ms:card_delete' card.id %}">Delete</a></td></tr>
        </form>

    
</table>

</td><td han="top">
    <table>
    {% for scan in scans %}

			<td align="center">
				<a href="{% static scan.image.name %}"><img height="300" src="{% static scan.image.name %}" /></a>
                <br />
                {{scan.mismatch}}
                <br />
                <a href="{% url 'ms:scan_mismatch' scan.id %}">Mismatch</a>
                
                <!--
                <form action="" method="post">{% csrf_token %}
                    <input type="hidden" name="id" value="{{card.id}}" />
                    <input type="submit" value="Mismatch" />
                </form>
                -->
            </td>
    {% endfor %}
    </table>
</td></tr>
</table>
<br/>
{% endif %}


<!--
<table border="1">
	<tr>
		<th>position</th><th>Image</th><th>Remove</th>
	</tr>
	{% for scan in scans %}
		<tr>
			<td>
				{{scan.position}}
			</td>
			<td>
				<a href="{% static scan.image.name %}"><img height="100" src="{% static scan.image.name %}" /></a>
			</td>
			<td>
				{% if card %}
				<a href="{% url 'ms:scan_delete' scan.id %}">Remove!</a>
				{% endif %}
			</td>
		</tr>
	{% endfor %}
</table>
-->

{% endblock %}

magicsorter/ms/templates/ms/card_confirm_delete.html
{% extends 'ms/base.html' %}
{% block content %}

<h3>{{ object.id }} {{ object.name }}</h3>

<form action="{% url 'ms:card_delete' card.id %}" method="post">{% csrf_token %}
    <p>Are you sure you want to delete"?</p>
    <input type="submit" name="delete" value="Confirm!" />
</form>

{% endblock %}

magicsorter/ms/templates/ms/cards.html
{% extends 'ms/base.html' %}

{% block content %}

{% load staticfiles %}

<table border="0">
	{% for card in cards %}
        {% cycle '<tr>' '' '' '' %}
        	<td>
				<table border="1">
					<tr>
						<td colspan="2">
							<a href="{% url 'ms:card' card.id %}"><img height="100" src="{% static card.thumb.name %}" /></a>
						</td>
					</tr>
					<tr>
						<td>
							Id
						</td>
						<td>
							{{card.id}}
						</td>
					</tr>
					<tr><td>Count</td><td>{{card.count}}</td></tr>
					<tr><td>Outbox</td><td>{{card.outbox}}</td></tr>
					<tr>
						<td>
							Name
						</td>
						<td>
							{{card.name}}
						</td>
					</tr>
					<tr>
						<td>
							Price
						</td>
						<td>
							{{card.price}}
						</td>
					</tr>
                    <tr>
						<td>
							MTG code
						</td>
						<td>
							{{card.mtgcode}}
						</td>
					</tr>
                    <tr>
						<td>
							Rarity
						</td>
						<td>
							<b>{{card.rarity}}</b>
						</td>
					</tr>

            	</table>
            </td>
        {% cycle '' '' '' '</tr>' %}
	{% endfor %}
</table>

{% endblock %}

magicsorter/ms/templates/ms/scans.html
{% extends 'ms/base.html' %}

{% block content %}

{% load staticfiles %}
<h4>
Count {{ scans.count }}
</h4>

    {% for scan in scans %}


				<a href="{% static scan.image.name %}"><img height="300" src="{% static scan.image.name %}" /></a>
                <!--{{scan.mismatch}}
                <a href="{% url 'ms:scan_mismatch' scan.id %}">Mismatch</a>-->

    {% endfor %}



{% endblock %}